### ISSUE TITLE
转换chatglm3-6b模型失败

### ISSUE THREAD

**Issue by 791136190** [wangzhaode/llm-export#12]
命令用的："--path", "models/chatglm3-6b", "--type", "chatglm3-6b",  "--export_split", "--onnx_path", "onnx/chatglm3-6b"
报错如下，看着是因为kv cache只有一组数据

not enough values to unpack (expected 2, got 1)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 413, in forward
    cache_k, cache_v = kv_cache

**Comment by wangzhaode** [comment]
好的 我看一下

**Comment by wangzhaode** [comment]
你看下llm_model/chatgglm3-6b下的python文件是否拷贝到--path指定的文件夹下

**Comment by 791136190** [comment]
应该是拷贝了，不然的话if pytorch_major_version >= 2 and False:这里会不一样。我看了一下应该history的kv需要一个tuple，但是只输入了一组导致的，我在另外一个工程里面单独实现了导出，但是在你的工程里面加进去会有很其它问题，就没尝试了

**Comment by wangzhaode** [comment]
好吧 llm-export会把pastkv改成`torch.tensor`并且第一个维度是`2`; 所以对源文件进行了修改，看你的错误好像是没有修改或者后续又被改掉了导致的

**Comment by 791136190** [comment]
我今天又重新pull了代码并测试，还是一样的报错。cache_k, cache_v = kv_cache unpack失败。下面是我的一些pip包版本，会有关系吗？我是通过pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple安装的指定依赖
但是我注释掉了MNN==2.8.0，因为我暂时只需要onnx的文件测试

![image](https://github.com/wangzhaode/llm-export/assets/27891060/341c6039-43ca-4b03-a211-93d5be9253a5)

**Comment by wangzhaode** [comment]
> 我今天又重新pull了代码并测试，还是一样的报错。cache_k, cache_v = kv_cache unpack失败。下面是我的一些pip包版本，会有关系吗？我是通过pip install -r requirements.txt -i [https://pypi.tuna.tsinghua.edu.cn/simple安装的指定依赖](https://pypi.tuna.tsinghua.edu.cn/simple%E5%AE%89%E8%A3%85%E7%9A%84%E6%8C%87%E5%AE%9A%E4%BE%9D%E8%B5%96) 但是我注释掉了MNN==2.8.0，因为我暂时只需要onnx的文件测试
> 
> ![image](https://private-user-images.githubusercontent.com/27891060/294067547-341c6039-43ca-4b03-a211-93d5be9253a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUzNTIsIm5iZiI6MTcwNDMzNTA1MiwicGF0aCI6Ii8yNzg5MTA2MC8yOTQwNjc1NDctMzQxYzYwMzktNDNjYS00YjAzLWEyMTEtOTNkNWJlOTI1M2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMmFjZDgyMzI0ZGE0N2ZiOWM0NGViMTE2ZWYyZDNkZDg3ZTUzMDAzMGFlYjZjZTQ3ZjZiZWNmMWY5YmE3YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OKAT0OJlwP6Z_I-KruzW1Sd7yraC60_bW2T9CnfwBy0)

你在代码里打印一下past_kv的shape看下是多少呢

**Comment by wangzhaode** [comment]
我看了下确实是搞错了 这个shape写错了 是在支持phi-2的时候不小心把这个shape也改成phi-2的了，这个应该是：
self.past_kv_shape = [28, 2, 0, 1, 2, 128]

你先修改了就可以导出了

**Comment by wangzhaode** [comment]
我修复下

**Comment by 791136190** [comment]
> 我看了下确实是搞错了 这个shape写错了 是在支持phi-2的时候不小心把这个shape也改成phi-2的了，这个应该是： self.past_kv_shape = [28, 2, 0, 1, 2, 128]
> 
> 你先修改了就可以导出了

嗯。我先修改尝试一下。感谢回复

**Comment by wangzhaode** [comment]
d91c83fa87b4a39f3596bc5f5f9e7cd63b337849

已修复
