### ISSUE TITLE
onnxslim优化onnx模型

### ISSUE THREAD

**Issue by inisis** [wangzhaode/llm-export#13]
大佬好，我这边维护了一个onnx模型优化工具，[OnnxSlim](https://github.com/inisis/OnnxSlim)，针对大模型推理会有一定提升。例如qwen 1.8b 的block模块，优化结果如下：

```
onnxslim block_9.onnx block_9_slim.onnx --model_check optimization --input_shapes past_key_values:2,1,0,16,128
```

![image](https://github.com/wangzhaode/llm-export/assets/46103969/b2c9e1a4-6d87-4389-bbfa-26c445ac08cb)

希望后面可以一起开发，一起进步。

**Comment by DavidQiuChao** [comment]
你做的onnx op融合和冗余去除， MNN转换的时候会不会也做了？

**Comment by wangzhaode** [comment]
赞👍🏻！ 可以加到代码中，导出onnx后使用slim优化一下

**Comment by inisis** [comment]
the latest version of onnxslim can have better optimization result

![image](https://github.com/wangzhaode/llm-export/assets/46103969/0f2952ff-4037-42d1-badd-2facb04da25d)
