### ISSUE TITLE
Qwen-VL 的release是否有误？

### ISSUE THREAD

**Issue by JennieGao-njust** [wangzhaode/llm-export#17]
https://github.com/wangzhaode/llm-export/releases/tag/qwen-vl-onnx/lm.onnx   只有500多Bytes吗？ 是否是正常的

**Comment by JennieGao-njust** [comment]
使用onnx2mnn函数直接转这个lm.onnx,报错Segmentation fault

**Comment by LLH-Harward** [comment]
lm.onnx只是最后的argmax部分吧 这个是分阶段导出的

**Comment by JennieGao-njust** [comment]
> lm.onnx只是最后的argmax部分吧 这个是分阶段导出的
直接用release的的lm.onnx来导出mnn,也报错Segemntation fault ,看了一下 Qwen-7B 的lm.mnn,是200M左右；您这边是能成功转换vl的lm head的mnn
吗？

**Comment by JennieGao-njust** [comment]
> lm.onnx只是最后的argmax部分吧 这个是分阶段导出的

lm.onnx里面是4096到词表的线性层

**Comment by wangzhaode** [comment]
lm.onnx 与 visual.onnx 文件超过2GB； lm.onnx仅上传了计算图，没有上传权重；

**Comment by wangzhaode** [comment]
防止误解我还是删除掉吧

**Comment by wangzhaode** [comment]
> 使用onnx2mnn函数直接转这个lm.onnx,报错Segmentation fault

weight size太大了 超除了int范围，MNN需要做一下bugfix

**Comment by JennieGao-njust** [comment]
> 防止误解我还是删除掉吧



> lm.onnx 与 visual.onnx 文件超过2GB； lm.onnx仅上传了计算图，没有上传权重；



> > 使用onnx2mnn函数直接转这个lm.onnx,报错Segmentation fault
> 
> weight size太大了 超除了int范围，MNN需要做一下bugfix

是4096*151693？ 这里是怎么超出了呢

**Comment by JennieGao-njust** [comment]
> > 防止误解我还是删除掉吧
> 
> > lm.onnx 与 visual.onnx 文件超过2GB； lm.onnx仅上传了计算图，没有上传权重；
> 
> > > 使用onnx2mnn函数直接转这个lm.onnx,报错Segmentation fault
> > 
> > 
> > weight size太大了 超除了int范围，MNN需要做一下bugfix
> 
> 是4096*151693？ 这里是怎么超出了呢

是指的字节大小超出了吗 4096*151693*4 ？  我看Qwen-7B-chat官方给了mnn结果
