### ISSUE TITLE
Qwen2-0.5B模型MNN转换问题

### ISSUE THREAD

**Issue by zihaoguo0724** [wangzhaode/llm-export#47]
请问qwen2模型，想转成https://modelscope.cn/models/zhaode/Qwen2-0.5B-Instruct-MNN/files 这种格式的，执行的llm_export.py的参数应该怎么写？
谢谢!

**Comment by wangzhaode** [comment]
`python llm_export.py --path $dir --export --export_embed --embed_bin --export_token`
