### ISSUE TITLE
qwen2-vl 转成onnx 后有使用示例吗？

### ISSUE THREAD

**Issue by iwaitu** [wangzhaode/llm-export#58]
qwen2-vl 转成onnx 后有使用示例吗？

**Comment by wangzhaode** [comment]
有mnn的例子，可以参考mnn的例子来写onnx的代码

**Comment by wangzhaode** [comment]
https://github.com/wangzhaode/onnx-llm

新增了onnx-llm的项目。后续为增加qwen2-vl的onnx示例
