### ISSUE TITLE
qwen2-vl 转成 onnx 后，如何再通过 tensorrt 单独把 visual 部分转成 plan ？

### ISSUE THREAD

**Issue by scdotbox** [wangzhaode/llm-export#59]

**Comment by wangzhaode** [comment]
> 如何再通过 tensorrt 单独把 visual 部分转成 plan 

这个句话的意思不太明白？导出之后就会有`visual.onnx`模型的

**Comment by wangzhaode** [comment]
目前还没有测试过

**Comment by dreamjp2022** [comment]
> 我试了下现在可以转为 visual.onnx，请问下现在有试过转为 tensorrt 吗？

我转出来的visual.onnx只有1.3M，然后有很多visual开头的文件，不知道怎么使用。你这边转出来是多大的文件？

**Comment by wangzhaode** [comment]
> > 我试了下现在可以转为 visual.onnx，请问下现在有试过转为 tensorrt 吗？
> 
> 我转出来的visual.onnx只有1.3M，然后有很多visual开头的文件，不知道怎么使用。你这边转出来是多大的文件？

因为模型大小超过2GB，onnx会把权重和计算图单独存储
