### ISSUE TITLE
作者你好，转换Qwen2-0.5B-Instruct到onnx时，打印graph.node有重复权重？

### ISSUE THREAD

**Issue by LLIKKE** [wangzhaode/llm-export#61]
创建`session = ort.InferenceSession(onnx_model_path, providers=['CUDAExecutionProvider'])`时，出现`Error: two nodes with same node name`问题。

运行：
```
import onnx
# 加载 ONNX 模型
model = onnx.load('E:\Desktop\llm-export-master\llmexport\model\onnx\llm.onnx')

# 获取模型的计算图
graph = model.graph

# 打印模型中每个节点的名称
print("ONNX model layers (nodes) names:")
for node in graph.node:
    print(node.name)
```
会出现：
```
/layers.0/self_attn/q_proj/Linear
/layers.0/self_attn/q_proj/Linear
/layers.0/self_attn/k_proj/Linear
/layers.0/self_attn/k_proj/Linear
/layers.0/self_attn/v_proj/Linear
/layers.0/self_attn/v_proj/Linear
```

**Comment by LLIKKE** [comment]
补充：
```
==================================================
Node Name: /layers.1/self_attn/q_proj/Linear
  Op Type: MatMul
  Inputs: ['/input_layernorm_1/Mul_1_output_0', '/layers.1/self_attn/q_proj/Linear_weight']
  Outputs: ['/layers.1/self_attn/q_proj/Linear_matmul']
  Attributes: []
==================================================
Node Name: /layers.1/self_attn/q_proj/Linear
  Op Type: Add
  Inputs: ['/layers.1/self_attn/q_proj/Linear_matmul', '/layers.1/self_attn/q_proj/Linear_bias']
  Outputs: ['/FakeLinear_4_output_0']
  Attributes: []
```

**Comment by wailokkwok** [comment]
same error, and lead to this error during later inference

FAIL : This is an invalid model. Error: two nodes with same node name (/layers.0/self_attn/q_proj/Linear).

This is the code

import numpy as np
from PIL import Image
import onnx
from onnxruntime import InferenceSession

onnx_model = onnx.load('/home/matthew_kwok_tictag_io/gotocr/model/onnx/llm.onnx')
sess = InferenceSession(onnx_model.SerializeToString())
image = Image.open('/home/matthew_kwok_tictag_io/gotocr/2024032916390700.jpeg')
input_img = np.array(image)
outputs = sess.run(None, {'input': input_img})
print(outputs)

**Comment by wangzhaode** [comment]
我看一下这个问题(ﾟﾍﾟ?)

**Comment by DzAvril** [comment]
同样的问题，Qwen2-1.5b-instruct，插个眼

**Comment by wangzhaode** [comment]
是一个bug，出错的原因是在重构计算图时bias的加法操作名字跟MatMul重复了

https://github.com/wangzhaode/llm-export/blob/3bb1ab11b83ebcb2c2c9b079947d97248d2b2559/llmexport/llmexport.py#L428

**Comment by wangzhaode** [comment]
fixed in https://github.com/wangzhaode/llm-export/commit/5b462ce002ebe3a7ec935973dd7659ec36592d70
