### ISSUE TITLE
onnxslim 0.1.35,onnx 1.16.1 转换出错

### ISSUE THREAD

**Issue by cqray1990** [wangzhaode/llm-export#62]
/onnxslim/cli/_main.py", line 6, in <module>
    def slim(model: Union[str, onnx.ModelProto], *args, **kwargs):
AttributeError: module 'onnx' has no attribute 'ModelProto'

**Comment by inisis** [comment]
see https://github.com/tsingmicro-toolchain/OnnxSlim/issues/32
