### ISSUE TITLE
qwen2 VL模型导出onnx后position ids为什么只有两维了

### ISSUE THREAD

**Issue by 404805854** [wangzhaode/llm-export#63]
您好，qwen2 vl的position ids 按照transformers代码实现和论文描述应该是三维的，但是目前导出的onnx好像是llm的单纯range，没有图像维度的位置编码，这样对图像是否会存在问题？如果没有问题能不能受累提供一份python的onnx推理代码？

**Comment by wangzhaode** [comment]
position ids是文本的位置编码，图像的编码固定在visual.onnx模型中了
