### ISSUE TITLE
export_split的支持

### ISSUE THREAD

**Issue by Benjamin039** [wangzhaode/llm-export#65]
请问现在不支持将onnx模型分割的--export_split的选项了吗

**Comment by wangzhaode** [comment]
是的 这个选项目前删除掉了

**Comment by Benjamin039** [comment]
请问后续还会考虑支持吗

**Comment by wangzhaode** [comment]
> 请问后续还会考虑支持吗

mnn-llm目前也不支持分段的模型了，所以llm-export也不会支持了；如果你有需求可以fork这个仓库，参考之前的代码，添加一个函数就可以了

**Comment by wangzhaode** [comment]
因为分段模型的性能相比完整的模型会有损失，所以废弃了分段模型的导出和推理
